### ISSUE TITLE
APP: Gitea updated & Mycelium inside

### ISSUE THREAD

**Issue by xmonader** [threefoldtech/tf-images#202]

**Comment by PeterNashaat** [comment]
- after researching for latest gitea versions found out this  https://github.com/go-gitea/gitea/tree/main/contrib/environment-to-ini, my idea is to use env-to-ini to make it easier for gitea configuration deployment, now i'm creating gitea flist which will contain gitea docker-compose file with a bash script that will collect env passed to the flist and start the gitea compose file with these env's.

- Created env-init.sh script which will create a .env file with all gitea related env that starts with `Gitea__`  same Prefix as used [here](https://github.com/go-gitea/gitea/tree/main/contrib/environment-to-ini) 
```
#!/bin/bash

# Prefix to look for
PREFIX="GITEA__"

# The path to the .env file
ENV_FILE="/docker/.env"
# Making sure file is empty
> "$ENV_FILE"

env > /tmp/env_export.txt

while IFS='=' read -r name value ; do
  if [[ $name == $PREFIX* ]]; then
    echo "$name='$value'" >> "$ENV_FILE"
  fi
done < /tmp/env_export.txt

# Cleanup the temp file
rm /tmp/env_export.txt

echo "GITEA environment variables saved to $ENV_FILE"
```

- Created this docker-compose file which will start 
```
version: "3"

networks:
  gitea:
    external: false

services:
  server:
    image: gitea/gitea:latest
    container_name: gitea
    environment:
      - USER_UID=1000
      - USER_GID=1000
      - GITEA__database__DB_TYPE=postgres
      - GITEA__database__HOST=db:5432
      - GITEA__database__NAME=${GITEA_DATABASE_DB:-gitea}
      - GITEA__database__USER=${GITEA_DATABASE_USER:-gitea}
      - GITEA__database__PASSWD=${GITEA_DATABASE_PASSWORD:-gitea}
    restart: always
    networks:
      - gitea
    volumes:
      - ./gitea:/data
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    ports:
      - "${GITEA__server__HTTP_PORT:-3000}:3000"
      - "${GITEA__server__SSH_PORT:-222}:22"
    env_file:
      - .env
    depends_on:
      - db

  db:
    image: postgres:14
    restart: always
    environment:
      - POSTGRES_DB=${GITEA__database__NAME:-gitea}
      - POSTGRES_USER=${GITEA__database__USER:-gitea}
      - POSTGRES_PASSWORD=${GITEA__database__PASSWD:-gitea}
    networks:
      - gitea
    volumes:
      - ./postgres:/var/lib/postgresql/data
    env_file:
      - .env
```
- Tested the docker-compose and the env-init.sh script 
<img width="954" alt="image" src="https://github.com/threefoldtech/tf-images/assets/13523434/702bda66-b730-4d09-8813-40500e228e9d">

<img width="1017" alt="image" src="https://github.com/threefoldtech/tf-images/assets/13523434/894b719b-3d46-42f0-bee6-8cc0c516ff09"> 

- Working on a way to https the setup and i have 2 options 
   - Use https://docs.gitea.com/administration/config-cheat-sheet#server-server with env config that will automatically https the setup from the docker-compose side
```
GITEA__server__PROTOCOL=https
GITEA__server__DOMAIN=example.gitea.domain
GITEA__server__HTTP_PORT=3000
GITEA__server__ROOT_URL=https://example.gitea.domain:3000/
``` 
or if used caddy it will be like this 
```
GITEA__server__PROTOCOL=http
GITEA__server__DOMAIN=your.gitea.domain
GITEA__server__ROOT_URL=http://your.gitea.domain/
```
  -  Or use reverse proxy like caddy and use`GITEA__server__DOMAIN=your.gitea.domain`  in Caddyfile config
```
${GITEA__server__DOMAIN} {
    reverse_proxy localhost:3000
}
```
```both ways need to be tested first ```

- All config files are pushed to tf-images repo https://github.com/threefoldtech/tf-images/commit/4a98a8658471ed03623401deef54d5bfa0e00188

Still in progress
